In [5]:
import numpy as np 
import pandas as pd

In [10]:
data= {"A": [1,np.nan,3,4], "B": [5,6,7,np.nan], "C": [9,10,11,12]}

df=pd.DataFrame(data, index=["a","b","c","d"])

In [ ]:
# find missing data in a DataFrame
# removing missing data from a DataFrame
# filling missing data in a DataFrame

In [11]:
print(df.isna())

       A      B      C
a  False  False  False
b   True  False  False
c  False  False  False
d  False   True  False

In [12]:
print(df.isna().sum())

A    1
B    1
C    0
dtype: int64

In [13]:
print(df.isna().any())

A     True
B     True
C    False
dtype: bool

In [14]:
print(df.dropna())

     A    B   C
a  1.0  5.0   9
c  3.0  7.0  11

In [20]:
df.dropna(thresh=2)

     A    B   C
a  1.0  5.0   9
b  NaN  6.0  10
c  3.0  7.0  11
d  4.0  NaN  12

In [24]:
df.fillna({"A":0})

     A    B   C
a  1.0  5.0   9
b  0.0  6.0  10
c  3.0  7.0  11
d  4.0  NaN  12