In [1]:
import pandas as pd 
import numpy as np

In [2]:
df= pd.DataFrame({'A':[1,2,3,4,5,6],   'B':[10,20,30,40,50,60], 'C':[100,200,300,400,500,600]})


print(df)

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500
5  6  60  600

In [14]:
df.shape

(6, 3)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       6 non-null      int64
 1   B       6 non-null      int64
 2   C       6 non-null      int64
dtypes: int64(3)
memory usage: 276.0 bytes

In [11]:
df.describe()

              A          B           C
count  6.000000   6.000000    6.000000
mean   3.500000  35.000000  350.000000
std    1.870829  18.708287  187.082869
min    1.000000  10.000000  100.000000
25%    2.250000  22.500000  225.000000
50%    3.500000  35.000000  350.000000
75%    4.750000  47.500000  475.000000
max    6.000000  60.000000  600.000000

In [12]:
df.columns

Index(['A', 'B', 'C'], dtype='str')

In [ ]:
# print(df['A'] +10)

0    11
1    12
2    13
3    14
4    15
5    16
Name: A, dtype: int64

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500
5  6  60  600

In [21]:
df["A"] = df['A'] + 10
print(df)

    A   B    C
0  61  10  100
1  62  20  200
2  63  30  300
3  64  40  400
4  65  50  500
5  66  60  600

In [25]:
def square(x):
    return x**2

df["D"]=df["B"].apply(square)

print(df)

    A   B    C     D
0  61  10  100   100
1  62  20  200   400
2  63  30  300   900
3  64  40  400  1600
4  65  50  500  2500
5  66  60  600  3600